$(function(){
    $('.menu__bnt').on('click', function(){
		$('.header__menu-list').toggleClass('header__menu-list--active')
	});
    $('.best__pricing__grid-item__1').hover(
        function(){
            $('.best__pricing__grid-item__1').addClass('animation-on').removeClass('animation-off');
            $('.best__pricing__price1').addClass('animation-on2').removeClass('animation-off2');
            $('.best__pricing__text1').addClass('animation-on3').removeClass('animation-off3');
            $('.best__pricing__mini__text1').addClass('animation-on4').removeClass('animation-off4');
        },
        function(){
            $('.best__pricing__grid-item__1').removeClass('animation-on').addClass('animation-off');
            $('.best__pricing__price1').removeClass('animation-on2').addClass('animation-off2');
            $('.best__pricing__text1').removeClass('animation-on3').addClass('animation-off3');
            $('.best__pricing__mini__text1').removeClass('animation-on4').addClass('animation-off4');
        }
    );
    $('.best__pricing__grid-item__2').hover(
        function(){
            $('.best__pricing__grid-item__2').addClass('animation-on').removeClass('animation-off');
            $('.best__pricing__price2').addClass('animation-on2').removeClass('animation-off2');
            $('.best__pricing__text2').addClass('animation-on3').removeClass('animation-off3');
            $('.best__pricing__mini__text2').addClass('animation-on4').removeClass('animation-off4');
        },
        function(){
            $('.best__pricing__grid-item__2').removeClass('animation-on').addClass('animation-off');
            $('.best__pricing__price2').removeClass('animation-on2').addClass('animation-off2');
            $('.best__pricing__text2').removeClass('animation-on3').addClass('animation-off3');
            $('.best__pricing__mini__text2').removeClass('animation-on4').addClass('animation-off4');
        }
    );
    $('.best__pricing__grid-item__3').hover(
        function(){
            $('.best__pricing__grid-item__3').addClass('animation-on').removeClass('animation-off');
            $('.best__pricing__price3').addClass('animation-on2').removeClass('animation-off2');
            $('.best__pricing__text3').addClass('animation-on3').removeClass('animation-off3');
            $('.best__pricing__mini__text3').addClass('animation-on4').removeClass('animation-off4');
        },
        function(){
            $('.best__pricing__grid-item__3').removeClass('animation-on').addClass('animation-off');
            $('.best__pricing__price3').removeClass('animation-on2').addClass('animation-off2');
            $('.best__pricing__text3').removeClass('animation-on3').addClass('animation-off3');
            $('.best__pricing__mini__text3').removeClass('animation-on4').addClass('animation-off4');
        }
    );
    $('.best__pricing__grid-item__4').hover(
        function(){
            $('.best__pricing__grid-item__4').addClass('animation-on').removeClass('animation-off');
            $('.best__pricing__price4').addClass('animation-on2').removeClass('animation-off2');
            $('.best__pricing__text4').addClass('animation-on3').removeClass('animation-off3');
            $('.best__pricing__mini__text4').addClass('animation-on4').removeClass('animation-off4');
        },
        function(){
            $('.best__pricing__grid-item__4').removeClass('animation-on').addClass('animation-off');
            $('.best__pricing__price4').removeClass('animation-on2').addClass('animation-off2');
            $('.best__pricing__text4').removeClass('animation-on3').addClass('animation-off3');
            $('.best__pricing__mini__text4').removeClass('animation-on4').addClass('animation-off4');
        }
    );
    $('.advantages__item1').hover(
        function(){
            $('.advantages__item1').addClass('animation-on11').removeClass('animation-off11');
        },
        function(){
            $('.advantages__item1').removeClass('animation-on11').addClass('animation-off11');
        }
    );
    $('.advantages__item2').hover(
        function(){
            $('.advantages__item2').addClass('animation-on22').removeClass('animation-off22');
        },
        function(){
            $('.advantages__item2').removeClass('animation-on22').addClass('animation-off22');
        }
    );
    $('.advantages__item3').hover(
        function(){
            $('.advantages__item3').addClass('animation-on33').removeClass('animation-off33');
        },
        function(){
            $('.advantages__item3').removeClass('animation-on33').addClass('animation-off33');
        }
    );
    $('.advantages__item4').hover(
        function(){
            $('.advantages__item4').addClass('animation-on44').removeClass('animation-off44');
        },
        function(){
            $('.advantages__item4').removeClass('animation-on44').addClass('animation-off44');
        }
    );
    $('.last__post-list').slick({
        prevArrow: '<button type="button" class="slick-prev slick-btn"><img src="images/arrowleft.svg" alt=""></button>',
        nextArrow: '<button type="button" class="slick-next slick-btn"><img src="images/arrowright.svg" alt=""></button>',
    });
})